### ISSUE TITLE
How to request this setup?

### ISSUE THREAD

**Issue by deltafactory** [spectrumvoip/stratus-web-responder-weather#1]
The link in the README links to the main website. When asked, the support team does not know that the WebResponder exists.

How can a customer format their request so that it is routed to someone who can make it happen?

**Comment by spectrumvoip** [comment]
Wow, We didn't expect someone to find this before we could disseminate it out to the support folks.

The best way would be to email support @ spectrumvoip.com.  Put "Web Responder" in the subject and make sure you include the URI to your API.

We are still working the details out but in our testing:

1. We can point DIDs directly at it for outside your domain.
2. We can dial codes at it for inside your domain.
3. Untested but I'm pretty sure we'll be able to make it an option off of your API.

Get that ticket open and if you still have problems, let me know the ticket number back here and I'll help.

Thanks,

**Comment by deltafactory** [comment]
Thanks! The ticket is #173468.

**Comment by deltafactory** [comment]
Support has been in touch and this is moving forward - thank you for your assistance.

Are there docs that I can refer to besides what is in the README? I'm interested in the options for the verbs, as well as the data passed to the WebResponder on the initial request: caller info, keys pressed, IVR source ID, etc.

**Comment by spectrumvoip** [comment]
Thanks for the update.

When get you a call pointed at it, watch the GET parameters that are sent when Stratus makes the API call.  The request will contain details about the call.  It will tell you the caller and things like that.  I watched my Apache access_log.  

We'll add this to the README shortly:

When Stratus requests back to your WebResponder application (inbound or outbound), the URL always contains at least the following parameters:

- NmsAni : caller, e.g., "1001"
- NmsDnis : callee e.g., "2125551212"
- AccountUser : Account User
- AccountDomain : Account Domain
- AccountLastDial : Last Dialed Digits by the Account User
- Digits : Received Digits
- OrigCallID : (1-1188b)
- TermCallID : (1-1188b)
- ToUser : User Part input to the Responder
- ToDomain : Domain Part input to the Responder


Regards,

**Comment by spectrumvoip** [comment]
Hey,

I have to delete this repo and rebuild it.

So this issue will go away.

Just a heads up.

Regards,
