### ISSUE TITLE
Backwards incompatible PHP/XML

### ISSUE THREAD

**Issue by deltafactory** [spectrumvoip/stratus-web-responder-weather#2]
This line will break on PHP configurations where short tags are allowed:
https://github.com/spectrumvoip/stratus-web-responder-weather/blob/master/index.php#L6

This can be fixed by separating the ? and the </> characters.

**Comment by spectrumvoip** [comment]
Thanks for letting me know.

Can you give me the exact syntax your changed it to?

I tried several variations and couldn't figure it out in my limited time.

Regards,

**Comment by deltafactory** [comment]
This is what I'm using:
`echo '<' . '?xml version="1.0" encoding="UTF-8" standalone="no" ?' . '>';`

**Comment by spectrumvoip** [comment]
That broke mine.

Does this work on yours?

`echo "<?xml version='1.0' encoding='UTF-8' standalone='no' ?>";`

**Comment by spectrumvoip** [comment]
`echo "<?xml version='1.0' encoding='UTF-8' standalone='no' ?>";`

**Comment by deltafactory** [comment]
I don't know why the exact line I provided wouldn't work. I am using it in production. Perhaps conflicting use of single and double quotes.

The source of the conflict is that <? and ?> are PHP tags as well. They can't safely be together in a PHP script unless it's for that purpose.

Your version, fixed:
`echo "<" . "?xml version='1.0' encoding='UTF-8' standalone='no' ?" . ">";`

**Comment by spectrumvoip** [comment]
Thanks.  That works for my web server as well.  So I have it in the code now.

Regards,
