### ISSUE TITLE
Stability issues?

### ISSUE THREAD

**Issue by deltafactory** [spectrumvoip/stratus-web-responder-weather#4]
I have had multiple instances where a call will not hit the WebResponder URL. Trying again a minute later works as expected. I'm not sure where the error is occurring but I have no request in my logs so I don't think it's on my end.

**Comment by spectrumvoip** [comment]
If you are firewalling somehow by IP, know that the http request might be coming from two different ranges of IPs.  You can open a ticket to get those ranges.

If that isn't it, please open a ticket with the details of the issue.

1. Time and date.
2. calling and called numbers.
3. End result ( fast busy / recording / etc ).

The ticked will need to be escalated to look at our logs to see if we can see a problem on our side.

Regards,

**Comment by deltafactory** [comment]
There are no firewall rules in place. Detail has been added to the existing thread.
